name: jazzy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
          
jobs:
  jazzy-devel-ci:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - jazzy
        docker_image:
          - ubuntu:nobel
        include:
          - docker_image: ubuntu:nobel
            ros_distribution: jazzy
            ros_version: 2
    #container:
    #  image: ${{ matrix.docker_image }}
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.3.5
        with:
          package-name: natnet_ros2
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
      #- name: Setup directories
      #  run: mkdir -p ros_ws/src
      #- name: checkout
      #  uses: actions/checkout@v3
      #  with:
      #    path: ros_ws/src
      
      
